### ISSUE TITLE
Test-target names unique and don't build tests of dependencies (by default)

### ISSUE THREAD

**Issue by Dominik-K** [EVerest/EVerest-archived#129]
@gberardi-pillar started to synchronize the naming of the test-targets:

> everest-core cannot build with tests (BUILD_TESTING=ON) due to submodules having generic names that collide when CMake runs.
> This change makes the test target for [project name] unique by naming it after the repo, a pattern that can be followed for all repos.
> [...]
> I also used the Modern CMake pattern of enabling tests only if the project is the main project (not a child of a parent project) or if it is explicitly specified with cmake -Deverest-framework_BUILD_TESTING=ON to allow flexibility.

[He mentioned](https://lists.lfenergy.org/g/everest/message/1167) (in the mailing-list) https://cliutils.gitlab.io/modern-cmake/chapters/testing.html which looks like a good best-practice document. In there, the prefix-approach is used.

## Changes

1. In `/tests`-dir's `CMakeLists.txt`:
    ```cpp
    set(TEST_TARGET_NAME ${PROJECT_NAME}_tests)
    add_executable(${TEST_TARGET_NAME})
    // etc.
    ```
2. In repo's root `CMakeLists.txt`:
    ```cpp
    if( (CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME AND BUILD_TESTING) OR ${PROJECT_NAME}_BUILD_TESTING ) 
       include(CTest)
       // [...]
    ```
3. In `dependencies.yaml` (idea by @hikinggrass from https://github.com/EVerest/libevse-security/pull/30):
    ```yaml
    gtest: #or `catch2`
      cmake_condition: "BUILD_TESTING OR PROJECT_NAME_BUILD_TESTING"
    ```

RFC @a-w50 @hikinggrass 

## Tasks
- [ ] https://github.com/EVerest/everest-framework/pull/140
- [ ] https://github.com/EVerest/libevse-security/pull/28
- [ ] ... other repos TBD

**Comment by shankari** [comment]
@Dominik-K the best-practice document has

```
if((CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME OR MYPROJECT_BUILD_TESTING) AND BUILD_TESTING)
```

but you propose

```
if( (CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME AND BUILD_TESTING) OR ${PROJECT_NAME}_BUILD_TESTING)
```

Can you clarify the reason for the change? Concretely, BUILD_TESTING = False, but MYPROJECT_BUILD_TESTING = True,
- best practice will not run the test
- your code will

**Comment by Dominik-K** [comment]
1. You can use the common `cmake -D BUILD_TESTING=on` for each repo resp. CMake-project without any need to modify it. 
  ~~With the book's approach you've mentioned, you would always need to run a different (and longer) command based on the project (e.g. `cmake -D everest-framework_BUILD_TESTING=on -D BUILD_TESTING=on`).~~ It's common for both approaches (thx @gberardi-pillar for spotting this).
2. If you also want to build the tests of a dependency, then you can explicitly activate it, too. But normally you won't need this. I.e. I support [@gberardi-pillar's 2nd approach](https://github.com/EVerest/everest-framework/pull/140#issuecomment-1864533285):
    > I trust that those dependencies ran their own tests before they reached the point of being used by a parent repo [...]
    
Note: We're only talking about _building_ the tests. There might (didn't check it) also be adaptions needed for _running_ the tests in dependencies.

**Comment by gberardi-pillar** [comment]
To be clear, with the book's approach, if you specify only BUILD_TESTING=on and are building everest-framework specifically, then "CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME" would evaluate to true, so there is no need to specify the everest-framework_BUILD_TESTING variable. 

You would only specify that variable if you were building a parent project such as everest-core and desired to build the tests for the framework with it, at which point you are specifically going out of your way to say you want tests (BUILD_TESTING=ON) and that you want subproject tests to be built as well. 

I am unclear on how the alternative approach results in better desired behavior? It looks identical either way for the use cases I can think of (maybe we need to be specific & document what those use cases are), and the only differences are for uses cases I don't think make sense.

It boils down to "(A OR B) AND C" vs "(A AND C) OR B", right? Building out the truth tables (using Wolfram Alpha), in the first example, BUILD_TESTING=ON is a requirement to run tests, although not sufficient, but 

<img width="196" alt="image" src="https://github.com/EVerest/EVerest/assets/54074967/aae89194-6f91-4ddc-81c0-d0fc525260b0">

vs

<img width="189" alt="image" src="https://github.com/EVerest/EVerest/assets/54074967/589d6e46-9915-4aa6-822f-dcc8723f243d">


If building just the framework, then in the first proposed code from Modern CMake, we don't build the tests if specifying everest-framework_BUILD_TESTING without BUILD_TESTING. And I think that is fine, because why are you being so specific but not saying you want BUILD_TESTING? We could also always modify the CMake file so that if everest-framework_BUILD_TESTING is set, then set BUILD_TESTING, but I think defaulting to "BUILD_TESTING=ON means you want tests" is better than having two variables that could independently mean the same thing.

If building a parent project, then in the first proposed code from Modern CMake, we don't build tests if we don't have BUILD_TESTING=ON but do have everest-framework_BUILD_TESTING=ON. I think this is sensible, too, as what does it mean to build framework tests if you aren't building tests in the first place?

So I think both approaches are identical where it matters (although "where it matters" might depend on how we standardize on cmake usage and build configuration norms), and my main argument for the first approach is that it might appear more common in the wild and so new people joining the project who might be familiar with this pattern from other projects will have an easier time. Otherwise, they might need to spend time figuring out what is different.

**Comment by Dominik-K** [comment]
Thanks @gberardi-pillar for discussing this in today's working-group call :+1: That helped.

> To be clear, with the book's approach, if you specify only BUILD_TESTING=on and are building everest-framework specifically, then "CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME" would evaluate to true, so there is no need to specify the everest-framework_BUILD_TESTING variable.

Right, thx. So my first point is obsolete (updated my comment above).

So the difference is with my approach you would have one more freedom, i.e. that you could _only_ build tests of a dependency within the parent repo but not the tests of the parent itself. E.g. build only tests of `libocpp` (dependency), but not the tests of the `everest-core` (parent).

As we couldn't think of a use-case for additionally building the tests for the dependencies anyway, I'm fine to use the "Modern CMake"-approach now, too.

**Comment by andistorm** [comment]
I opend a PR to add this as best practice in our documentation
https://github.com/EVerest/EVerest/pull/132

@Dominik-K , @gberardi-pillar Could you have a look at it and acknowledge it?

**Comment by andistorm** [comment]
Agreed on https://everest.github.io/nightly/general/faq.html#testing

repos to be adapted:
- [ ] everest-core: https://github.com/EVerest/everest-core/pull/528
- [ ] libocpp: https://github.com/EVerest/libocpp/pull/301
- [x] libevse-security: https://github.com/EVerest/libevse-security/pull/28
- [ ] libfsm: https://github.com/EVerest/libfsm/pull/9
- [x] everest-framework: https://github.com/EVerest/everest-framework/pull/140 & https://github.com/EVerest/everest-framework/pull/136
- [x] libmodbus: https://github.com/EVerest/libmodbus/pull/17
- [x] libZVT: https://github.com/EVerest/libZVT/pull/1
- [x] libtimer: https://github.com/EVerest/libtimer/pull/8
- [ ] liblog: https://github.com/EVerest/liblog/pull/16
- [x] libslac: https://github.com/EVerest/libslac/pull/6
