### ISSUE TITLE
Refactor: Clean up docker images

### ISSUE THREAD

**Issue by andistorm** [EVerest/EVerest-archived#178]
## Target of this issue

Target is to implement a unified strategy for docker images in EVerest. This means to decide on which flavours we want to provide/support for docker images, where we want to locate Dockerfiles, which purposes we want to cover, for which platforms we push built images to container registry.

## Current State

Currently there are multiple locations (everest-utils, everest-ci, everest-demo) where a lot of Dockerfiles are defined. In some cases there are multiple flavours for one use case. In other cases there are duplicated Dockerfiles for the same purpose.

### Dockerfiles in EVerest

* **everest-ci-env** (everest-utils): used as ci env for building and deploying documentation in EVerest/EVerest
* **everest-docker-image** (everest-utils): 2-staged Dockerfile to deploy/package EVerest in a docker image
* **everest-docu** (everest-utils): devcontainer to write documentation with local preview
* **everest-playground** (everest-utils): debian based devcontainer
* **everest-playground-opensuse-tumbleweed** (everest-utils): opensuse based devcontainer
* **everest-playground-ubuntu-22.04** (everest-utils): ubuntu based devcontainer
* **steve** (everest-utils): maven based Dockerfiles that installs steve
* **manager** (everest-demo): based on build-kit-alpine, builds everest-core
* **mosquitto** (everest-demo): based on eclipse-mosquitto, installs custom mosquitto.conf
* **nodered** (everest-demo): based on nodered/node-red, installs flows and add some nodered extensions
* **steve** (everest-demo): maven based Dockerfiles that installs steve
* **build-kit-alpine** (everest-ci): alpine based build kit to build everest-core
* **build-kit-debian** (everest-ci): debian based build kit to build everest-core
* **everest-clang-format** (everest-ci): debian based, includes run script for clang-format, used in ci to do linting

### Other docker related files in EVerest

* **mosquitto config** (everest-utils): Used in docker-compose.yml
* **docker-compose.yml** (everest-utils): Includes: mosquitto, ocpp-db, steve and nodered
* **everest-cpp** dir (everest-utils): working dir for devcontainer

### Keep it simple (debian based images)

Dockerfiles should be based on `debian` or on other EVerest images. This allows to have a docker base which is close to the most local environments (ubuntu, or other debian based distros). Dbeian is quite stable and allows to do reproducible builds.

### Do reusable builds (base images on others)

Implement a few base image on which most other images can base on

| Purpose                   | name                  | base              | description                                                   |
| --------------------------|-----------------------|-------------------|---------------------------------------------------------------|
| Runtime Base Image        | runtime-base          | debian:12         | Provides all runtime deps                                     |
| Build Kit Base Image      | build-kit-base        | runtime-base      | Provides all runtime + build deps                             |
| Devcontainer Image        | devcontainer          | build-kit-base    | Provides additional dev tools                                 |
| Build kit for each repo   | build-kit-<reponame>  | build-kit-base    | Modifies build-kit to fit indiviual reqs (mainly adding deps) |

## Consequences

* ❌ **`everest-ci-env`** (everest-utils): replace with `build-kit-doc` based on `build-kit-base`
* ➡️ **`everest-docker-image`** (everest-utils): ~~merge into everest-demo~~
  - keep for now
* ❌ **`everest-docu`** (everest-utils): replace with `devcontainer`
* ♻️ **`everest-playground`** (everest-utils): refactor and rename to `devcontainer`
* ❌ **`everest-playground-opensuse-tumbleweed`** (everest-utils): replace with `devcontainer`
* ❌ **`everest-playground-ubuntu-22.04`** (everest-utils): replace with `devcontainer`
* ♻️ **`manager`** (everest-demo): merge with `everest-docker-image` and rename to sth like `packaged-everest` or `deployed-everest` and base on `runtime-base`
* ❌ **`build-kit-alpine`** (everest-ci): replace with `build-kit-base` or `build-kit-<reponame>` in specifc use cases
* ♻️ **`build-kit-debian`** (everest-ci): refactor and rename to `build-kit-base`
* ➡️ **`everest-clang-format`** (everest-ci): merge into `build-kit-base`
* 🆕 **`runtime-base`**
* 🆕 **`build-kit-base`**
* 🆕 **`devcontainer`**
* 🆕 **`build-kit-<reponame>`**

## Open Questions

- [x] Do we still need to run steve image (everest-utils) locally?
  - Yes
- [x] Do we need to run steve image for everest-demo?
  - Yes
- [x] Do we need to push customized `mosquitto`, `nodered` and `steve` to `ghcr.io`?
  - not necessarily, but can reduce ci run time
- [x] How do we want to provide the devcontainer technically?
  - devcontainer base pushed to ghcr.io & Dockerfile to enable local modifications

## TODOS

Runtime related:
- [ ] Merge `everest-docker-image` with `manager` into `everest-demo`/`packaged-everest` -> Create dedicated issue with detailed requirements
- [x] Add `runtime-base`

Build kit related:
- [x] Refactor `build-kit-debian` to `build-kit-base`
- [x] Merge `everest-clang-format` into `build-kit-base`
- [x] Add `build-kit-<reponame>` images to all repositories

Devcontainer related:
- [x] Refactor devcontainer images

Common:
- [x] Remove unneeded Dockerfiles

**Comment by Pietfried** [comment]
Nice overview!

I would suggest to provide services like SteVe, Nodered and mosquitto as part of the devcontainer image, so that you can use them inside your devcontainer if needed.

Concerning the everest-docker-image: Since this is still used within other projects, lets keep it for now and base this on the new images when those are ready. We can then decide where to move it or if we still need it.

**Comment by andistorm** [comment]
@Pietfried @hikinggrass, Could you give a quick thumb up or your thoughts on:
What do you think about prefixing all images with the repository name, so currently the full name is like `ghcr.io/everest/everest-clang-format` or `ghcr.io/everest/build-kit-alpine`. I propose to switch to
`ghcr.io/<org-name>/<repo-name>/<image-name>` so for example `ghcr.io/everest/everest-ci/build-kit` 

The reason for this is the versioning. Since it makes sense to keep the version tags of the docker iamges in sync (automatically) with the git tags they are kind of bound to the repo. When moving a single docker image in future the tag history wouldn't make sense anymore.

**Comment by andistorm** [comment]
While doing the refactoring the Consequences and TODOs are updated:

## Consequences

* ❌ **`everest-ci-env`** (everest-utils): replace with `build-env-evverest` based on `build-env-base`
* ➡️ **`everest-docker-image`** (everest-utils): ~~merge into everest-demo~~ keep for now
* ❌ **`everest-docu`** (everest-utils): replace with `devcontainer`
* ♻️ **`everest-playground`** (everest-utils): refactor and rename to `devcontainer`
* ❌ **`everest-playground-opensuse-tumbleweed`** (everest-utils): replace with `devcontainer`
* ❌ **`everest-playground-ubuntu-22.04`** (everest-utils): replace with `devcontainer`
* ♻️ **`manager`** (everest-demo): ~~merge with `everest-docker-image` and rename to sth like `packaged-everest` or `deployed-everest` and base on `runtime-base`~~ keep for now
* ❌ **`build-kit-alpine`** (everest-ci): replace with `build-kit-base` or `build-kit-<reponame>` in specifc use cases
* ♻️ **`build-kit-debian`** (everest-ci): refactor and rename to `build-kit-base`
* ➡️ **`everest-clang-format`** (everest-ci): merge into `build-kit-base`
* 🆕 **`run-env-base`**
* 🆕 **`build-env-base`**
* 🆕 **`build-kit-base`**
* 🆕 **`dev-env-base`**
* 🆕 **`devcontainer`**
* 🆕 **`build-kit-<reponame>`**

## TODOS

Runtime related:
- [x] Add `run-env-base` image
  * https://github.com/EVerest/everest-ci/pull/22

Build kit related:
- [x] Add `build-env-base` image
  * https://github.com/EVerest/everest-ci/pull/22
- [x] Remove `build-kit-alpine`
  * https://github.com/EVerest/everest-ci/pull/22
- [x] Refactor `build-kit-debian` to `build-kit-base`
  * https://github.com/EVerest/everest-ci/pull/22
- [x] Merge `everest-clang-format` into `build-kit-base`
  * https://github.com/EVerest/everest-ci/pull/22
- [x] Add `build-kit-<reponame>` images to all repositories
  - [x] `build-env-everest` -> everest/everest
    * https://github.com/EVerest/EVerest/pull/183
  - [x] `build-kit-everest-core`
    * https://github.com/EVerest/everest-core/pull/770
  - [ ] More other repositories
- [x] Remove `everest-ci-env`
  * https://github.com/EVerest/EVerest/pull/183

Devcontainer related:
- [x] Add `dev-env-base` image
  * https://github.com/EVerest/everest-ci/pull/22
- [x] Refactor `everest-playground` to `devcontainer`
  * https://github.com/EVerest/everest-dev-environment/pull/45
  * https://github.com/EVerest/everest-utils/pull/152
- [x] Remove `everest-playground-opensuse-tumbleweed`
  * https://github.com/EVerest/everest-utils/pull/152
- [x] Remove `everest-playground-ubuntu-22.04`
  * https://github.com/EVerest/everest-utils/pull/152
- [x] Remove `everest-docu`
  * https://github.com/EVerest/everest-utils/pull/152
